# Generated by Django 5.2.5 on 2025-08-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='bank_name',
            new_name='name_company',
        ),
        migrations.RenameField(
            model_name='paymentitems',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='paymentitems',
            name='amount',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentitems',
            name='operation_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
