# Generated by Django 5.2.5 on 2025-08-26 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_bank_name_paymentdetails_name_company_and_more'),
        ('core', '0002_floor_flat_house_gallery_section_floor_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MeasurementUnit_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_name', models.CharField(max_length=255)),
                ('tariff_description', models.TextField()),
                ('last_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('installation_date', models.DateField()),
                ('is_active', models.BooleanField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.flat')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.house')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.section')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('status', models.CharField(max_length=255)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.meter')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.BooleanField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.flat')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.house')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.section')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='personal_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.personalaccount'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('create_date', models.DateField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('is_posted', models.BooleanField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.flat')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.house')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.section')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.personalaccount')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.personalaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(max_length=255)),
                ('MeasurementUnit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.measurementunit')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.service'),
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.service')),
            ],
        ),
        migrations.CreateModel(
            name='TariffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=50)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.service')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.tariff')),
            ],
        ),
    ]
