# Generated by Django 5.2.5 on 2025-08-26 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_measurementunit_tariff_meter_meterreading_and_more'),
        ('core', '0002_floor_flat_house_gallery_section_floor_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.tariff'),
        ),
    ]
