# Generated by Django 5.2.5 on 2025-08-26 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_measurementunit_tariff_meter_meterreading_and_more'),
        ('core', '0003_flat_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.tariff'),
        ),
    ]
