# Generated by Django 5.2.5 on 2025-08-27 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enforce_tariff_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='core.floor'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='core.section'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.house'),
        ),
        migrations.AlterField(
            model_name='section',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.house'),
        ),
    ]
