# Generated by Django 5.2.5 on 2025-08-26 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutPageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages/about/')),
                ('section', models.CharField(max_length=255)),
                ('AboutPage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('site', models.URLField()),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('map', models.CharField(max_length=255)),
                ('SEO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.seo')),
            ],
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='SEO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.seo'),
        ),
        migrations.CreateModel(
            name='ShowcasePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('main_image_1', models.ImageField(upload_to='pages/showcase/')),
                ('main_image_2', models.ImageField(upload_to='pages/showcase/')),
                ('main_image_3', models.ImageField(upload_to='pages/showcase/')),
                ('SEO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.seo')),
            ],
        ),
        migrations.CreateModel(
            name='TariffPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('SEO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.seo')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages/blocks/')),
                ('caption', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ShowcasePage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.showcasepage')),
                ('TariffPage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.tariffpage')),
            ],
        ),
    ]
