# Generated by Django 5.2.5 on 2025-08-26 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_floor_flat_house_gallery_section_floor_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('comment', models.TextField()),
                ('preferred_time', models.DateTimeField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.flat')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_requests', to=settings.AUTH_USER_MODEL)),
                ('master_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=255)),
                ('Body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('only_debtors', models.BooleanField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.flat')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.floor')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.house')),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.section')),
            ],
        ),
    ]
